language: cpp

compiler:
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:boost-latest/ppa; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi

install: make ext

script: make all

branches:
  only:
    - master

notifications:
  email: true
    - firmament-dev@camsas.org

env:
  - NONINTERACTIVE="1"

os:
  - linux
